# Generated by Django 2.1.1 on 2019-03-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
