# Generated by Django 2.1.1 on 2019-02-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_activity_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Post'),
        ),
    ]
