# Generated by Django 2.1.1 on 2019-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20190202_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
