# Generated by Django 2.1.1 on 2019-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20190205_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(),
        ),
    ]
