# Generated by Django 2.1.1 on 2019-02-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20190205_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
